### ISSUE TITLE
Feature Request: Disable Spring Boot auto config if migration not enabled

### ISSUE THREAD

**Issue by Dimibe** [michael-simons/neo4j-migrations#1171]
Hello, 
I came across the issue that even if with `org.neo4j.migrations.enabled=false` the Spring Boot auto config will load at startup. 
This is normally not an issue since the migration itself does not run. But in some cases, an unexpected behavior can occur.  

E.g. at startup the method [neo4jMigrationsConfig](https://github.com/michael-simons/neo4j-migrations/blob/main/neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfiguration.java#L60) will be called, which can lead to an exception [here](neo4jMigrationsConfig) if the other migrations properties are not well-defined. 

In contrast [this](https://github.com/michael-simons/neo4j-migrations/blob/main/neo4j-migrations-spring-boot-starter-parent/neo4j-migrations-spring-boot-autoconfigure/src/main/java/ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfiguration.java#L89) bean for example will only load if the migrations are enabled.  So I wonder if we can apply the condition on class level or at least prevent the possible exception if migrations are disabled?

**Comment by michael-simons** [comment]
Hi,

thanks for raising this. If there's no config, I cannot give you to `Migrations` bean at all.

The only exception that can be thrown from the other method should be if the migrations are  - as you write - not in place.

Doesn't help setting `org.neo4j.migrations.check-location` to `false` then? 

Btw I see you are located in Aachen (I am too)? Are you able to share about your use case?

**Comment by Dimibe** [comment]
Hi, 
thanks for your feedback.
Yes, setting `org.neo4j.migrations.check-location` to `false` helped. I just wondered because I thought disabling the migrations would prevent any configuration on startup.  

Yes you're right, I'm also located in Aachen. Seems to be a small world :D 
My use case is that I use the migrations only for development through Spring Boot. Elsewhere I use the binary inside my deployment process as you already suggested to my [in this comment](https://github.com/michael-simons/neo4j-migrations/issues/1081#issuecomment-1727838514).

Since I use Testcontainers at development time I just came to the conclusion that I could change the migrations dependency to test scope. This way it's still usable during development and completely excluded in production builds.

**Comment by michael-simons** [comment]
Sorry for getting back late to you.
So, I first thought you only want to disable validation, now I understand you don't want the migration itself.

You can set

```org.neo4j.migrations.enabled = false```

in your Spring Boot config: That will disable Neo4j-Migrations on startup, but will still give you both a `ac.simons.neo4j.migrations.core.Migrations` and a `ac.simons.neo4j.migrations.core.MigrationsConfig` bean with which you can interact if needed.

If this helps, please close the ticket :) 

Eitherway, kind regards and all the best for 2024.

**Comment by Dimibe** [comment]
Hi and thanks, 

yes, your answer helped me. Seems that I missed the use case of having the migration beans available while the migration itself disabled.  I will close the ticket. :)  

Wishing you a Happy New Year!

**Comment by michael-simons** [comment]
Thank you, Dimitrios and same to you!
