### ISSUE TITLE
enable import options for index creation by catalog(xml)

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1182]
Hallo,
I am trying to import indexes by catalog (xml).
The normal/simple ones work like a charm, but for some I need to change the analyzer.
The xml format has a tag <options> for indexes, but after looking futher into it, the RenderConfig.CypherRenderingOptions has it hardly deactivated.
Is there an easy/good way to activate it? I have done it by override a class and hardly setting the value on RenderConfig. Not a good approach, but its working :)

**Comment by michael-simons** [comment]
can you help me understand what you trying to achieve by a code / config example? Maybe we can add the appropriate API.

**Comment by shanon84** [comment]
sure, I have the following index definition in my catalog migration script:
      <index name="myFulltextIndex" type="fulltext">
        <label>MyNode</label>
        <properties>
          <property>myFulltextSearchProperty</property>
        </properties>
        <options>
          indexConfig: +{ `fulltext.analyzer`:"whitespace" }
        </options>
      </index>
The migration ignores all in <options>, because the default RenderConfig always returns false for importing the options. And I cannot see an easy way to override the default RenderConfig or even change something in it from outside.
Maybe enhance the CatalogBasedMigration to access the MigrationConfig and set the importOption after creating the RenderConfig

**Comment by michael-simons** [comment]
I have added a test in the above linked commit showing the designed usage.  Does this help?

**Comment by shanon84** [comment]
hey,
sry for the late response:
I am using the spring autoconfiguration. I have the MigrationConfig in hand, but nothing else.
I understand your test and the way to handle it, but to be able to use it, I need to copy/reprogram the hole Migration class. Exspecially if I want to still use the xml migration approach.

Is there a reason, why options in index creation are hardly ignored? I mean, you can always not add options, if you dont want them.

**Comment by michael-simons** [comment]
Thanks for clarifying. Got your point now, added the ability to configure that on the config. 

For Spring Boot you can now add a customizer to the config, so that you don't need to overwrite that bean as a whole (that allows you to keep the Spring Boot config as is, using application.properties, yaml or whatever you like) and just customize what you need, like this:

```java
@Bean
	ConfigBuilderCustomizer configBuilderCustomizer() {
		return configBuilder -> configBuilder.withConstraintRenderingOptions(List.of(new RenderConfig.CypherRenderingOptions() {
			@Override
			public boolean includingOptions() {
				return true;
			}
		}));
	}
```
