### ISSUE TITLE
catalog annotation for fulltext index

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1184]
Hey, its me again.

After thinking about your solution regarding the index creation (inclusive options) in the last issue:
I have found no way to create an index with the annotation processor, other than the old ogm annotations. The sdn6 and the catalog annotations do not include anything.
Thats why I have implemented a new annotation @FulltextIndex:
#https://github.com/michael-simons/neo4j-migrations/pull/1183

It should generate normal fulltext indexes and also allows to set a custom analyser.
If you like it, feel free to change/use it.

**Comment by michael-simons** [comment]
Closed with 09a6454dad073390d5afe13f41a14b92e8f0c18a
