### ISSUE TITLE
catalog generator does not working with foreign annotation

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1189]
Hey,

I have found a bug with the catalog generator.
Open the testmodel CoffeeBeanSDN6. Add a foreign annotation to the class (@SuppressWarning for example).
The catalog annotation constraints are no longer generated. (see CatalogGeneratingProcessorTest)
I believe the problem resides in CatalogGeneratingProcessor.processCatalogAnnotation:
the annotationsPresent is compared with equals against the possible SN6 or OGM annotation. If you use contains, it works like a charm.

**Comment by michael-simons** [comment]
🤦‍♂️  excellent catch, quite stupid mistake. Thank you.

**Comment by michael-simons** [comment]
@all-contributors please add @shanon84 for error

**Comment by michael-simons** [comment]
@all-contributors please add @shanon84 for bug
