### ISSUE TITLE
Migrations's resources support for correct versioning ordering 

### ISSUE THREAD

**Issue by pepow** [michael-simons/neo4j-migrations#1212]
Hi, 

we use tool for migration for Neo4j, works quite well, but we've found issue for versioning of migration's resources. Problem is that tool make ordering of versions for resources by lexicographic order. Reason for that is implementation of "MigrationVersion.VersionComparator" (and comparing by java.lng.String compare method). Would be really useful to be able sort by semantic versioning. 

**Example resources:**
V1.4.3__one.cypher
V1.4.2__one.cypher
V1.4.1__one.cypher
V1.16.1__one.cypher

**Expected behaviour:**
(after execeute ordering)
V1.4.1__one.cypher
V1.4.2__one.cypher
V1.4.3__one.cypher
V1.16.1__one.cypher

**Actual behaviour* 
V1.16.1__one.cypher
V1.4.1__one.cypher
V1.4.2__one.cypher
V1.4.3__one.cypher

Would be possible to added correct version comparator, or at least added support for that type of ordering ? Current probably we need to use workaround which force ut to name new resource in lexicographic manner. 

Thanks, 
Peter

**Comment by michael-simons** [comment]
Oh dear, thanks for your comment and thoughtful analysis. You are ofc right and I do think that’s a bug. Happy to either fix this later this month myself or incorporate any PR.

**Comment by michael-simons** [comment]
@all-contributors please add @pepow for error

**Comment by michael-simons** [comment]
@all-contributors please add @pepow for bug

**Comment by michael-simons** [comment]
Will be configurable from 2.9.0 on.

**Comment by michael-simons** [comment]
Hej Peter,

this will go out on Monday next week after a bunch of dependency updates.

Thanks again for the report.
