### ISSUE TITLE
Migration ordering: ignore ordering chain (option to migrate new scripts with lower versions)

### ISSUE THREAD

**Issue by pepow** [michael-simons/neo4j-migrations#1213]
Hi, 

is there any chance for implementing feature "ignoreOrdering" in future ? Feature means (same as Flyway migration tool) that new new scripts which are not tailing migration chain will be executed anyway (no matter where middle-or-tail). 
Of course user should be aware of dangerous impact on database, but still this feature is really usefull (for hotfix-ing producation where is need to create new script and also be able to merge back to development branch) 

There's workaround, by create next version and merge these scripts back to branches, but feature would be help to doing this in more effective way.

Thanks,
Peter

**Comment by guy-keller** [comment]
To add to the feature request - here are the docs from Flyway around this:  
https://documentation.red-gate.com/fd/out-of-order-224919730.html

Thank you very much

**Comment by michael-simons** [comment]
Thanks @guy-keller I hope my December will be a bit slower and I can pick this up, but I can't give any promises atm.

**Comment by michael-simons** [comment]
This is now implemented and will be released as 2.14.0.

**Comment by michael-simons** [comment]
@all-contributors 
please add @guy-keller for research
please add @pepow for ideas

**Comment by michael-simons** [comment]
@all-contributors please add @pepow for ideas
