### ISSUE TITLE
Neo4j-Migrations CLI Token Based Authentication Support

### ISSUE THREAD

**Issue by amit-kumaryadav** [michael-simons/neo4j-migrations#1227]
Hi @michael-simons, We are running the CLI based neo4j-migrations. But our requirement is to pass the token with CLI and that token is also expired in given time (Means if token is expired we need refresh token) and for that we are using Microsoft Authentication Library [MSAL] connect to neo4j. How can we achieve this ??

**Comment by michael-simons** [comment]
Hej Amit.

The CLI version can only use Username/Password auth atm and it it's in contrast to the core lib itself responsible to create the drivers instance.

Are you asking for a feature to support Neo4j token based auth? 

In your application, are you creating the driver with an `AuthToken` created through `AuthTokens.bearer()`?  If so, I can absolutely add this to the CLI.

**Comment by amit-kumaryadav** [comment]
@michael-simons Our application is based on Spring boot and there we are using Java driver and AuthTokens.bearer() to creating the driver. 
![2024-02-12 15_30_05-intelligent-stock-monitoring-system – Neo4jDriverConfig java  asset-editor (1)](https://github.com/michael-simons/neo4j-migrations/assets/36166686/154519d0-6197-4d8d-9c75-e7a63ff9c723)

**Comment by michael-simons** [comment]
Thanks!

I'll add the possibility to do this to the CLI this week.

**Comment by amit-kumaryadav** [comment]
Thanks @michael-simons

**Comment by michael-simons** [comment]
FYI you are using an outdated driver

https://github.com/neo4j/neo4j-java-driver/commit/c3b10e30b4d2553e37b931fc9e7c990ec1ee699d

I was looking for the methods you shared, they are changed ^^

I am not happy that the team did this on a minor and I am gonna communicate that back.

**Comment by michael-simons** [comment]
Hej Amit
we discussed this a bit.

a) I misread the adding / removing of preview annotations, so technically the team changed the method names during preview. But: You are still using an outdated driver, and you need to adapt when you update. This just as information
b) I am gonna support the bearer mechanism, but not the refresh. The expiration date you configure in your snippet is not the date at which the token expires, but at which the server/driver connection will attempt to retrieve a new one from the supplier you provided (the thing coming from getAuthToken). In a CLI there is no way to refresh that, even not through system variables, as they are immutable in the direction from parent to child process

For the functionally, see the PR attached. Thanks again.

**Comment by michael-simons** [comment]
This has been released as 2.9.1
