### ISSUE TITLE
Annotation processor does not respect @Id and @Property annotation

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1271]
Hey,

if you have the following node class member:

```java
	@Id
	@Property("myOtherIdName")
	private String myId;
```

the annotation processor generates a constraint for the property "myId" and not "myOtherIdName".

**Comment by michael-simons** [comment]
Nice catch, Torsten, thank you!

This will be fixed in 2.10.0, as this is a breaking change, "normal" properties are not treated correctly either.
