### ISSUE TITLE
repeatable migrations destroy migration chain

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1342]
Hey there,
we have the following setup:
a R001 (xml constraints)
a V002
a V003

we changed R001 and times after we added V004.

The problem is:
On a database with missing R001 update (and V004) the migration does the following:
update R001 (and add a selflink)
add V004 and create a link from R001! On the next start the migration crashes, because we have 2 follow up migrations after 001!

Best regards

**Comment by michael-simons** [comment]
So prior to failing, the database has

* V002
* V003
?

**Comment by michael-simons** [comment]
Thanks, @shanon84.

Bug-fix release is underway.
