### ISSUE TITLE
Add support for spring bean injection using java-based migrations

### ISSUE THREAD

**Issue by rugbroed** [michael-simons/neo4j-migrations#1393]
neo4jmigrations is supporting java-based migrations, however, not using spring bean injection.

_I would like to see something like this;_

```java
public class V0_0_1__MyPojoMigration implements JavaBasedMigration {
	private final Logger logger = LoggerFactory.getLogger(this.getClass());
	
	@Autowired
	private MyNeo4jRepository myNeo4jRepository;
 	
	@Override
	public void apply(MigrationContext context) {
		List<MyPojo> myPojos = myNeo4jRepository.findAll();
		
		...
	}
}
```

Thanks for a great project!

**Comment by michael-simons** [comment]
@all-contributors please add @rugbroed for ideas

**Comment by michael-simons** [comment]
Thanks for the cool idea.

To benefit from this in 2.11.0 you'll need to opt in by annotating the migrations in questions with a stereotype such as `@Component`.  

You can do this on a case by case basis, other migrations will still be loaded, and components have precedence.
