### ISSUE TITLE
Large Neo4j database timing out when using `neoj4-migrations info`

### ISSUE THREAD

**Issue by medsouz** [michael-simons/neo4j-migrations#1476]
We have a decently large Neo4j database (~500GB). Recently we noticed our migrations have been running slowly and consuming a large amount of memory. 

I managed to track it down to this query: https://github.com/michael-simons/neo4j-migrations/blob/089a16d94dbbe98c7f68bb21e1b66ac827acca94/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/ChainBuilder.java#L168-L173

After profiling the query I noticed it was specifically hanging on 
```cypher
OPTIONAL MATCH () - [r:REPEATED] -> ()
```

We don't have any repeated migrations in our database so as a shot in the dark I tried creating an index for that relationship:
```cypher
CREATE INDEX Neo4jMigrationsRepeated
FOR ()-[r:REPEATED]-()
ON (r.at);
```

This completely resolved our issue and now the tool is running speedily again.

I'm not entirely sure if this is an issue with our database configuration or a place where `neo4j-migrations` could be improved but I figured I'd share it here in case anyone else needs it.

**Comment by michael-simons** [comment]
Excellent catch. I think I should anchor that query on a node, that should help it. Otherwise the index on the schema database is indeed helpful. Can’t define it by default can I? Don’t know from the top of my head if relationship property indexes are in CE these days too. Will check tomorrow.

**Comment by michael-simons** [comment]
@all-contributors please add @medsouz for ideas

**Comment by michael-simons** [comment]
Fixed and released. Thanks again.

**Comment by medsouz** [comment]
Thanks for the quick turn around!
