### ISSUE TITLE
Target version to migrate

### ISSUE THREAD

**Issue by zakjan** [michael-simons/neo4j-migrations#1536]
Hi,

Is it feasible to add a feature to specify a target version to migrate to? Similar Flyway feature is called simply Target https://documentation.red-gate.com/fd/target-224919756.html

Use case: importing a database export from an older version. Due to database constraints that can be added in later versions, the export needs to be imported to a database with constraints created by the expected version and no later. Only then a subsequent migration can be run to migrate the database to the latest version.

**Comment by michael-simons** [comment]
Sure, that makes a lot of sense.

**Comment by michael-simons** [comment]
@all-contributors add @zakjan for ideas

**Comment by michael-simons** [comment]
🎁 comes early… this is released with 2.15.0, binaries will be on central soon, CLI and other binaries at the usual places.

**Comment by zakjan** [comment]
@michael-simons Oh wow, thanks, we'll test it this month!

Just one thing, I'm curious why the target version is defined by the filename prefix e.g. `V1_2_3` instead of what's stored in `__Neo4jMigration.version` property, e.g. `1.2.3`? Because this property `1.2.3` is what we store with the export metadata.

Anyway, that's solvable by replacing `.` to `_` and prefixing by `V` during import.

**Comment by michael-simons** [comment]
So that I can use the same algorithm when deriving the version from the filename like before essentially. 

If you think about the migration files as the common interface until now, it made sense to me that `V123__whatever` can also be (abbreviated) be used as `V123`.

**Comment by michael-simons** [comment]
If this proves to be an issue at your end, you can add the logic here

https://github.com/michael-simons/neo4j-migrations/blob/d8bbf8d9fced1d3b4df32f950391452b01979002/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationVersion.java#L119-L129

Basically replace the throw then with something like this

```
neturn new StopVersion(new MigrationVersion(versionThatIsUnsuredObeysToWhatIsStoredNormally, null, false), version.endsWith('?'));
```

and send me a PR :)
