### ISSUE TITLE
Version support for neo4j-migration

### ISSUE THREAD

**Issue by katya-dovgalets** [michael-simons/neo4j-migrations#159]
Thanks for creating such a helpful tool!

As neo4j-migration is based on Flyway, it will be great to support the full Flyway versions convention which is described here https://flywaydb.org/documentation/concepts/migrations#discovery
Especially, subversions (like V01.5__some_schema or  V01_5__some_schema) and other prefixes for different migration types like R and U.

Thanks a lot!

**Comment by michael-simons** [comment]
Thank you, for both issue and PR. I'll have a look this or next week.
