### ISSUE TITLE
Failed to load cypher migration from Spring Boot jar

### ISSUE THREAD

**Issue by ihordz** [michael-simons/neo4j-migrations#179]
Spring Boot 2.4.3, neo4j-migrations  0.1.2
The similar issue as  #89. 
_Invocation of init method failed; nested exception is ac.simons.neo4j.migrations.core.MigrationsException: Could not read script file jar:file:/app/service.jar!**/BOOT-INF/classes!/BOOT-INF/classes**/neo4j/migrations/schema/V0001__init_constraints.cypher_

Workaround -  override classgraph version to 4.8.90.
Looks like the reason is the changes in  [classgraph-4.8.91](https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.91).

**Comment by michael-simons** [comment]
Thanks @ihordz  See https://github.com/classgraph/classgraph/issues/505. 

I have to invest some time into my CI so that I notice that upfront. It doesn't happen when the example has not been packaged up.

**Comment by michael-simons** [comment]
I have put out 0.1.3 with the upgraded Classgraph that fixes your issue. Also: Finally a decent integration test, which is kinda hard actually, as one has to make sure that the packaged "fat" jar is used and not single resources and classes. 

Should be on central soonish.
