### ISSUE TITLE
Mac OS line endings (single `\r`) are not treated correctly.

### ISSUE THREAD

**Issue by AndreasBoehme** [michael-simons/neo4j-migrations#232]
When executing DB-Migrations in different environments (Windows, Linux), the current systems' line-ending is taken into account of the checksum (i.e. `\r\n` vs `\r`).
When the DB-data is copied to another environment, validation fails due to different checksums (of the previously applied script and the same script with different endings in another environment).

**Comment by michael-simons** [comment]
Hi @AndreasBoehme Thanks for raising this. Technically it could be an easy fix, but I have to think about how to not make this a breaking change for everyone.

**Comment by AndreasBoehme** [comment]
@michael-simons thanks for your fast reply!

One way, that would not break anything would be to introduce a config-param - e.g. *validateOnMigrate=[true|false]* to turn off checksum-validation at all. Flyway defines that exact property (and I think this lib was inspired by flyway): https://flywaydb.org/documentation/configuration/parameters/validateOnMigrate

However, if you find a better solution, that would be fine, too ;-) I used flyway a few years ago and something that bugged a lot was exactly that: doing validations but ignoring line-endings wasn't possible.

**Comment by michael-simons** [comment]
Yeah, turning it off completely is one way, or "ignore line endings" is another (set to false by default).

**Comment by michael-simons** [comment]
Hmm… @AndreasBoehme can you please check if you do actually have a single `\r` (CR)?
Files with `\n` and `\r\n`  are treated equal. 
Of if anything else did change while transporting these files.

**Comment by AndreasBoehme** [comment]
Hi @michael-simons,

unfortunately that change does *not* fix the issue.

I turned on the debugger and still see the `\r\n` as part of the statement - only at the end it's stripped off. I guess this is because I use multi-line statements, similar to your example in the README.adoc:

```
UNWIND RANGE(1,6) AS i
WITH i CREATE (n:OtherAgents {idx: '00' + i})
RETURN n
; // <----- /r/n is removed from this line, not from the others
```

**Comment by michael-simons** [comment]
Thanks for the additional pointers. 

As a workaround, please use the new option to disable validation.

**Comment by michael-simons** [comment]
This is a very good read https://github.com/flyway/flyway/issues/253 I should have seen like 2 years ago :D
