### ISSUE TITLE
Reported version on Aura defaults to patch version 0

### ISSUE THREAD

**Issue by meistermeier** [michael-simons/neo4j-migrations#449]
Migrations outputs `4.4.0` instead of `4.4-aura` due to the fact that the server version gets parsed by the driver.

Also the same outcome can be seen in the browser.
![image](https://user-images.githubusercontent.com/435872/157720539-5227ccb3-ee8d-4d32-86ed-2f429a8846ab.png)

Maybe we should do our own version parsing from the `dbms.components()` output.

**Comment by michael-simons** [comment]
No, I wont go there. It's a mess as it is and it's wrong to add another layer of hand-weaving-obsfuscation. I happily adapt to handling of the returned version to this.
