### ISSUE TITLE
Crash when applying migrations to Aura

### ISSUE THREAD

**Issue by Hosch250** [michael-simons/neo4j-migrations#549]
The exception is: `java.lang.NumberFormatException: For input string: "4-aura"`.

Path is:
> https://github.com/michael-simons/neo4j-migrations/blob/07a115e8fc0908eec769b5e18dff4b7460aeaf3a/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/HBD.java#L47
> https://github.com/michael-simons/neo4j-migrations/blob/07a115e8fc0908eec769b5e18dff4b7460aeaf3a/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/internal/Neo4jVersionComparator.java#L30

Aura is returning `4.4-aura` as the version instead of `Neo4j/4.4`.

**Comment by michael-simons** [comment]
Thanks for the excellent catch.

I'll will release 1.8.2 shortly. Will this fit your usecase or do you need a lower version being updated? (Note: They are all compatible for a while, no breaking changes)

**Comment by Hosch250** [comment]
I think 1.8.2 would work. @mattborderux would know.

**Comment by michael-simons** [comment]
1.8.2 went out today.
