### ISSUE TITLE
Quarkus Dev-Ui is using wrong html container class.

### ISSUE THREAD

**Issue by michael-simons** [michael-simons/neo4j-migrations#566]
Doesn't match the UI anymore.

**Comment by michael-simons** [comment]
Only if you like of course @meistermeier not in a hurry.

**Comment by meistermeier** [comment]
After trying things out and comparing, I am not sure what exactly is meant.
The only real difference I see is the fluid layout used in all other (default) extensions.
Changing
```
{#include main}
```
into
```
{#include main fluid=true}
```
does the job.
But I think there is more. Of course we could finally add some fancy styling to the database text above the table ;)

**Comment by michael-simons** [comment]
Fixed with 35647817504e65b6fbcb0f33d942830c21b996a3
