### ISSUE TITLE
Support triggers for Neo4j Causal Clustering architecture.

### ISSUE THREAD

**Issue by SergeyPlatonov** [michael-simons/neo4j-migrations#572]
Neo4j-Migrations versions (tried 3 versions): **1.6.0, 1.8.0, 1.8.3**.
Neo4j version: **4.4.2 enterprise**.
Apoc version: **4.4.0.4**.

Used Neo4j-Migrations tool via CLI (Neo4j-Migrations-CLI).
Tried to apply triggers to the database. In the **standalone** version, all triggers, indexes, and constraints can be applied, but with clustering, I can't apply triggers using the apoc library.
I tried to run for example this command:
`CALL apoc.trigger.remove('testTrigger');`
Even if we don't have such a trigger, it should work. It does nothing, but runs without error.
We have a neo4j instance with 3 servers (cluster mode).
When I run this query, I get exceptions like this:

**version 1.6.0:**
_Could not unlock… Please check for residues (Nodes labeled `__Neo4jMigrationsLock`).
Could not ensure uniqueness of __Neo4jMigrationsLock. Please make sure your instance is in a clean state, no more than 1 lock should be there simultaneously!
	Neo.ClientError.Cluster.NotALeader: No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER_

**version 1.8.3 (bolt scheme):**
_Could not ensure uniqueness of __Neo4jMigrationsLock. Please make sure your instance is in a clean state, no more than 1 lock should be there simultaneously!
	Neo.ClientError.Cluster.NotALeader: No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER_
	
_Could not apply migration: 1.2.4 ("v2 user audit log triggers").
	Neo.ClientError.Cluster.NotALeader: No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER_

**version 1.8.3 (neo4j scheme):**
_Could not apply migration: 1.2.4 ("v2 user audit log triggers")._

I used different schemes (bolt, neo4j) and connected to all of our servers (3 servers).
By running these triggers through the UI (Neo4j browser), I can only apply them when connecting using **bolt scheme** and IP where the system database has the role **leader**. I expect that neo4j-migration should also work with such an address.

The command what was used:
**neo4j-migrations --username {user_name} --password {password} --address bolt://{IP}:7687 --database entitlements --location file:./scripts migrate**

**Comment by michael-simons** [comment]
Thanks for reporting this! I’ll look into this next week. In the meantime, can you provide one migration script and if possible the APOC call with a (dummy / shell) trigger?

I’m away from keyboard but I have one suspicion here: we are using transactional functions to execute scripts and APOC tries to outsmart everything and does it’s own transaction handling and I guess this is one of such cases.

**Comment by SergeyPlatonov** [comment]
[triggers.zip](https://github.com/michael-simons/neo4j-migrations/files/9161294/triggers.zip)
It can be any operation with add/remove/pause/resume for the apoc.trigger

And with **standalone** neo4j everything works fine. The exception appears only in cluster mode.

**Comment by michael-simons** [comment]
Thanks, @SergeyPlatonov !

Did you by coincidence check that standard Cypher (not calling APOC) works against your cluster? Not that there are issues with the driver. 

we are using explicit write transactions 
https://github.com/michael-simons/neo4j-migrations/blob/f50b3651830d5787768c3a721a55eef4259fcb17/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultCypherResource.java#L223

So the driver must Route them to leaders.

**Comment by michael-simons** [comment]
Hi @SergeyPlatonov 

So, for the triggers to work, you need correctly recognize you need to connect to the leader for the `systemdb` and for that you need to specificy bolt direct.
That leader is however not the leader fro the `entitlements` database, in which in this case also the migration information will be stored, including the lock. So the error happens already when trying to acquire a lock (exception gets swallowed which ist not good either)

First though is use `--schema-database` for that, but here the same restrictions will apply. 

I think that maybe a solution based on #559 could work. We will experiment a bit.

**Comment by michael-simons** [comment]
I might have bad news in store. I hoped that when I explicitly connect to the system database, i would be able to call the trigger related procedures, but the thought is flawed for two reasons:

* The trigger would be created for the system database itself (I guess at least, dunno how the apoc triggers work)
* System DB only has a restricted set of commands, see below

If I try to do 

```java
try(Driver driver = GraphDatabase.driver("neo4j://localhost:51377", AuthTokens.basic("neo4j", "secret"));
			Session session = driver.session(SessionConfig.forDatabase("system"))) {
			session.run("CALL apoc.trigger.add('test', \"CALL apoc.log.info('OK') RETURN 1\", { phase: 'after' });\n").consume();
		}
```

I'll end up with 

```
Exception in thread "main" org.neo4j.driver.exceptions.DatabaseException: Not a recognised system command or procedure. This Cypher command can only be executed in a user database: CALL `apoc`.`trigger`.`add`("test", "CALL apoc.log.info('OK') RETURN 1", {`phase`: "after"})
  YIELD `name`, `query`, `selector`, `params`, `installed`, `paused`
RETURN `name` AS `name`, `query` AS `query`, `selector` AS `selector`, `params` AS `params`, `installed` AS `installed`, `paused` AS `paused`
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:62)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:47)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:49)
```

So I don't see a solution for this library here.

`:use  different-db` won't do it, explicit connect statements per migrations won't do it and disabling the lock won't do it either (you wont see the error you have there, but as soon as you would have any other migration changing data, it would break. 

I really recommend reaching out to @jexp respectively open a new ticket at https://github.com/neo4j-contrib/neo4j-apoc-procedures. If the trigger related operations in APOC would do proper routing before trying to create / remove a trigger, things would work. 

I fully understand that this is frustrating for you, but the way the cluster with leaders and followers works and what APOC is trying to do here leaves me in a dead end while trying to offer a solution. I am not happy either.

**Comment by michael-simons** [comment]
On the plus side, I developed this

```
jbang https://github.com/michael-simons/junit-jupiter-causal-cluster-testcontainer-extension/blob/master/bin/start.java --neo4jVersion 4.4 --password secret --accept-license --plugin APOC --plugin BLOOM
```

for use with https://www.jbang.dev

**Comment by michael-simons** [comment]
> By  running these triggers through the UI (Neo4j browser), I can only apply them when connecting using bolt scheme and IP where the system database has the role leader. I expect that neo4j-migration should also work with such an address.

To answer your expectations: They are not correct. The moment you issue another write query in browser (such as creating any node etc), it will most likely fail and only succeed if and only if the same member of the cluster is both the leader for the systemdb and the entitlement database.

You might ask if u could use the system db to store the migrations metadata: No, because:

```
neo4j@system> create (n);
The following unsupported clauses were used: CREATE. 
The system database supports a restricted set of Cypher clauses. The supported clause structure for procedure calls is: CALL, YIELD, RETURN. YIELD and RETURN clauses are optional. The order of the clauses is fix and each can only occur once.
```

**Comment by SergeyPlatonov** [comment]
Hi @michael-simons 

Thanks for your investigation.
I checked this in the apoc library, they have several tickets on this topic.
I think they need to make some improvements to make this library work properly in cluster mode.

**Comment by michael-simons** [comment]
Sorry, Sergey, but I am gonna close this issue. There is little I can do from a middleware's perspective here.

**Comment by SergeyPlatonov** [comment]
I checked again and it works fine with cypher-shell with some cases.
So the same requests work through Neo4j UI and cypher-shell, but don't work with neo4j-migrations.
I think the problem is not only in the apoc library.

**Using cypher-shell and Neo4j UI:**

- neo4j protocol to any node gives: “Server at /address/ no longer accepts writes“
- bolt protocol to follower node gives: “No write operations are allowed directly on this database. Writes must pass through the leader. The role of this server is: FOLLOWER“
- **bolt protocol to leader node executes successfully queries**: in my case “CALL apoc.trigger.remove('dummyTrigger');“ or “CALL apoc.trigger.add('dummyTrigger', 'CREATE (f:Foo)',{});“.

NOTE: previously mentioned leader and follower of system database
