### ISSUE TITLE
Automate MAC_ARM64 releases to SDKMAN!

### ISSUE THREAD

**Issue by ali-ince** [michael-simons/neo4j-migrations#619]
I am on an M1 Macbook and when I try to install neo4j-migrations through sdkman, I get the following error;

```
❯ sdk install neo4jmigrations

Stop! neo4jmigrations 1.10.1 is not available. Possible causes:
 * 1.10.1 is an invalid version
 * neo4jmigrations binaries are incompatible with your platform
 * neo4jmigrations has not been released yet

Tip: see all available versions for your platform:

  $ sdk list neo4jmigrations
```

The command `sdk list neo4jmigrations` outputs only the following version, which I am able to install explicitly.

```
================================================================================
Available Neo4jmigrations Versions
================================================================================
     1.5.1
```

Any pointers/workarounds would be greatly appreciated :)

**Comment by michael-simons** [comment]
Hey @ali-ince Thanks for the ticket!
GitHub does not yet provide MacARM runners and I haven't succeeded on setting up one.

I have uploaded an ARM binary for the 1.10.1 to the release and also updated SDKMan! manually build on a private machine.

Please give me feedback if this works for you but keep the ticket open. Thank you!

**Comment by ali-ince** [comment]
Thanks for looking into it, but I believe there is a problem with the uploaded version, as it just quits with a killed message;

```
❯ neo4j-migrations
[1]    27080 killed     neo4j-migrations
```

I think we'll need to wait until github actions support the M1 arch.

**Comment by michael-simons** [comment]
The compressor I use does not work, I can reproduce this.
And while trying to fix the release on SDK Man, I completely broke it.
I will release a new version on monday. 

The binary I put up on Github works now.

**Comment by michael-simons** [comment]
@all-contributors add @ali-ince for usertesting

**Comment by michael-simons** [comment]
Linux ARM64 binaries are now published automatically. Same approach with a custom runner can be used eventually for Mac ARM binaries.

**Comment by michael-simons** [comment]
ARM64 binaries are the only binary produced ever since ARM64 became the default respectively only available option on Github Actions, so that issue resolved itself.
