### ISSUE TITLE
Add warning if migration file gets skipped due to not conforming to file name schema

### ISSUE THREAD

**Issue by SaschaPeukert** [michael-simons/neo4j-migrations#672]
We keep messing up with the double underscore in the file name. And this is quite hard to find later and figure out, why that migration was not executed. Especially the first time this happens. Maybe add a warning that neo4j-migrations skipped over a file that did not conform to the schema `V1_2_3__Add_last_name_index.(cypher|xml|java)` ?

**Comment by michael-simons** [comment]
Good idea. If this helps, wdyt about leaving this project a star :)
