### ISSUE TITLE
[Feature] Rerun the same Java migration

### ISSUE THREAD

**Issue by MaurizioCasciano** [michael-simons/neo4j-migrations#702]
I have written a `JavaBasedMigration` class and, since the migration code is dynamic (e.g. scanning all the domain classes to generate unique constraints on some annotated fields), I want it to be executed at every start of the application (Spring-Boot).
How can I do that?
Something like Liquibase `runAlways`

**Comment by michael-simons** [comment]
Hey. That is not (yet) possible. Good new feature. 

You might want to have a look at our annotation processor and rethink if you want to regenerate at every startup. 

But still, something like repeatable / run always could be useful. 

https://michael-simons.github.io/neo4j-migrations/current/#appendix_annotation

**Comment by MaurizioCasciano** [comment]
Thank you Michael, I'll have a look.

**Comment by MaurizioCasciano** [comment]
Hi, I had a look at the annotation processor, 
however, there are a few things that are not clear to me.

How could I use it to create catalogs/migrations for `@Nodes` with unique constraints?
I mean, should I use both [Spring-Data-Neo4j 6.3.5](https://docs.spring.io/spring-data/neo4j/docs/6.3.5/reference/html/) and [Neo4j-OGM Core](https://github.com/neo4j/neo4j-ogm)?
I'm asking this because considering the SDN6 docs https://docs.spring.io/spring-data/neo4j/docs/6.3.5/reference/html/#faq.sdn-related-to-ogm they explicitly mention that Neo4j-OGM is no more needed nor supported.

Considering this `Organization` class, how do I model it to generate a unique constraint for the name property?

```java
@Data
@Node
@NoArgsConstructor
@AllArgsConstructor
public class Organization {
    @Id
    @GeneratedValue
    private UUID id;

    // TODO: which annotation should I use?
    @NotEmpty
    private String name;
}
```
Is it ok to use `@org.neo4j.ogm.annotation.Index` as in https://github.com/michael-simons/neo4j-migrations/blob/main/extensions/neo4j-migrations-annotation-processing/processor/src/test/java/ac/simons/neo4j/migrations/annotations/proc/ogm/UniqueConstraintEntity.java#L32 but with a `@org.springframework.data.neo4j.core.schema.Node` ?

Or is there some other equivalent annotation to use with SDN6?

**Comment by michael-simons** [comment]
That’s a good point and an excellent question. No, you should not use both libraries at the same time. 

One way I have in mind is adding a small subset of the annotations as an independent (from both SDN6 and older OGM) library. 

Fancy open a separate ticket?

**Comment by MaurizioCasciano** [comment]
Sure. Just moved the important text to https://github.com/michael-simons/neo4j-migrations/issues/703

**Comment by michael-simons** [comment]
Thanks, Maurizio.

FWIW I started the following branch… https://github.com/michael-simons/neo4j-migrations/tree/issue/702 Might take a bit, though.

**Comment by MaurizioCasciano** [comment]
Thanks Michael.
I had a look and it looks very promising.
I'll try to have a look at how to contribute and how to setup the development environment.

I was just wondering if the naming convention pattern of the migration (e.g. "V1__a_b(runAlways)") file is not becoming a limitation, also considering that the parentheses are not valid characters for Java classes.

Maybe an ordered `MasterMigrationSet` could help to have a list of the migrations that will be applied while allowing more freedom for future evolutions.
Here is a JSON of what I'm thinking, something like this (maybe for both Cypher and Java ?):

```json
{
	"migrations": [
		{
			"id": "3490e835-2808-4895-b79c-2b54c52c138a",
			"author": "Neo4j Developer",
			"description": "Neo4j Java Migration Example",
			"options": ["RUN_ALWAYS"],
			"type": "Java",
			"path": "eu.project.config.neo4j.migrations.MyJavaMigration"
		},
		{
			"id": "20d4173a-52f6-4569-9361-4a5cedcdfd23",
			"author": "Neo4j Developer",
			"description": "Neo4j Cypher Migration Example",
			"options": ["RUN_ON_CHANGE"],
			"type": "Cypher",
			"path": "src/main/resources/config/neo4j/migrations/MyCypherMigration.cypher"
		}
	]
}
```
Maybe the author, description and options can be optional with default values.
And the type could be also detected by analyzing the path.

I hope it makes sense.
What do you think?

**Comment by michael-simons** [comment]
I would not derive these options from the class name for java based migrations as I thought it be more reasonable to add it to the interface don’t u think?

**Comment by MaurizioCasciano** [comment]
Yes, sure.
I was trying to think about a unique way to enable options for both migration types while maintaining the same naming convention for both types.

I would allow to enable migration options for Java classes by using some annotation, like
@RunAlways and @RunOnChange

As of now is it possible to mix them?
I'm getting an error with the maven plugin during the migration goal, complaining that it could not found a cypher migration locally while on the DB there was a Java migration applied previously.

**Comment by michael-simons** [comment]
I think I’ll reconsider my first approach and stick with the flyway way of thinking, which I do find easier https://flywaydb.org/documentation/tutorials/repeatable


And yes you can mix Cypher scripts, XML and Java based.

**Comment by michael-simons** [comment]
Hey @MaurizioCasciano This is now merged on on main. Will be released next week. 
FWIW the architecture gave it away that I can do this even in a patch.

**Comment by michael-simons** [comment]
@all-contributors please add @MaurizioCasciano  for ideas
