### ISSUE TITLE
Neo4j migration and SpringBoot

### ISSUE THREAD

**Issue by alexanoid** [michael-simons/neo4j-migrations#704]
Hi! I'm trying to migrate from LiquiBase to Neo4j migrations with my SpringBoot project.

This is my configuration:

```
spring.neo4j.authentication.username=${neo4j.username}
spring.neo4j.authentication.password=${neo4j.password}
spring.neo4j.uri=${neo4j.bolt.server.database.uri}

org.neo4j.migrations.locations-to-scan=classpath:neo4j/migrations
```

I also added resources/neo4j/migration folder and placed a V1_indexes.cypher file there.

At the application starup I may see the following output in the console:

```
2022-11-02 19:56:52.536  INFO 29056 --- [           main] a.s.n.m.core.Migrations.Startup          : neo4j-migrations/1.13.2 connected to 
neo4j@localhost:7687 (Neo4j/5.1.0 Community Edition)
Database: neo4j

```
but that's it. The actual migration from V1_indexes.cypher  is not applied. What am I doing wrong? Thank you!

**Comment by michael-simons** [comment]
It’s two underscores:

```
V1__indexes.cypher
```

see 

https://michael-simons.github.io/neo4j-migrations/current/#concepts_naming-conventions

and also 

https://github.com/michael-simons/neo4j-migrations/issues/672
