### ISSUE TITLE
:movie_camera: Please provide #nodes22 demo video support :pray: 

### ISSUE THREAD

**Issue by adriens** [michael-simons/neo4j-migrations#757]
# Context

I'm actually benching liquibase with neo4-migrations, and I know that you did present your tool on `#nodes22` but cannot seem to retrieve it.

# :pray: Feature request

Could you please add some video resources on the README, i a dedicated section of the project :grey_question: 

Thank you in advance for your help.

**Comment by michael-simons** [comment]
Sure. Here’s the demo repo
https://github.com/michael-simons/nodes2022

slides
https://speakerdeck.com/michaelsimons/neo4j-migrations-the-lean-way-of-applying-database-refactorings-to-neo4j-efa52ac1-85e1-4688-97f3-566fc78de6cd

video from that
https://youtu.be/5-j0xiVAeoM

Put first and foremost our docs
https://michael-simons.github.io/neo4j-migrations/current/

**Comment by adriens** [comment]
Thanks a lot :pray: 
Will you add these to the README or should I close the issue ?

**Comment by adriens** [comment]
Ths one too https://youtu.be/5-j0xiVAeoM

**Comment by michael-simons** [comment]
Hey, my pleasure. Yeah, maybe. Lemme think about it for a bit. 

Maybe makes sense.

**Comment by michael-simons** [comment]
Thanks for the idea, Adrien!

@all-contributors add @adriens for ideas
@all-contributors add @michael-simons for talk

**Comment by michael-simons** [comment]
@all-contributors add @adriens for ideas
@all-contributors add @michael-simons for talk

**Comment by adriens** [comment]
> @michael-simons
> 
> @adriens already contributed before to ideas
> 
> I've put up [a pull request](https://github.com/michael-simons/neo4j-migrations/pull/767) to add @michael-simons! tada

We are about to migrate our `csv` and `cypher` based load scripts to other solutions as our repo is graowing at a very fast pace and wee need to be able to protect our GH branches with CI.

I'll let you know about our experiences and feedback.

BtW : did you put somewhere a kind of benchmark between [`neo4j-migrations`](https://github.com/michael-simons/neo4j-migrations) and [`liquibase-neo4j`](https://neo4j.com/labs/liquibase/) ?

:point_right: For now, `neo4j-migrations` seems better packaged and very community-driven

**Comment by michael-simons** [comment]
Thanks. I explained our reasoning for the existence of this tool. It is unrelated to benchmark in terms of speed. That depends vastly and way more intensive on your cypher, database content and these kind of things

I wanted something that is easier to use in terms of dependencies, packaging and setup. 

Feature wise we are on par apart from undos (however, they require manual undos on liquidate, too). We are better packaged for CI.

Dependency wise liquibase-neo4j is working on a better solution (the author is actually a teammate of me).
