### ISSUE TITLE
:grey_question: ENUM (aka. CHECK CONTRAINT) support :thinking: 

### ISSUE THREAD

**Issue by adriens** [michael-simons/neo4j-migrations#768]
# :grey_question: Context

Actually we load a lot of `csv` files and third party contents, and I would like to add as much contraints as possible to ensure data quality.

On most relational databases, we can implement a kind of [`CHECK CONSTRAINT`](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS).

# :dart: The question

How should or could we implement that as part of a migration process... and cause it to fail in case the `CHECK CONSTRAINT` is not fullfilled ?

Thank you in advance for your help, as I did not find how to achieve this as pure core cypher statement.

**Comment by michael-simons** [comment]
This functionality is not available in neo4j itself. This tooling supports all the constraints and indexes you’ll find in the product and I’m happy to add support for further ones. I don’t think it’s a client tooling duty to ensure (check) constraints. 

That said, I personally would love to see this as part of our Schema support. Please raise an issue over there https://github.com/neo4j/neo4j
