### ISSUE TITLE
🙏 Add csv load support (aka. loadData )⚡ 

### ISSUE THREAD

**Issue by adriens** [michael-simons/neo4j-migrations#775]
# ❔ Context

Actually we are loading data into our Neo4J instance by : 

1. linking the `import` directlry
2. run `cypher` commands

This works perfectly well on a local instance but...

We want to  : 

✔️  Switch to a remote instance (client/server mode)
✔️  Make the load process cleaner as our loading process becomes everyday heavier (like we usually do with  `Liquibase` on relational databases)

Then we initially started to look at [Neo4j plugin for Liquibase](https://neo4j.com/labs/liquibase/)... but I like rather more the distribution of [neo4j-migrations](https://github.com/michael-simons/neo4j-migrations).

# 🎯  Feature request : `loadData` tag

Please implement a "kind of" [`loadData` tag](https://docs.liquibase.com/change-types/load-data.html)... so we could achieve that kind of thing : 

![image](https://user-images.githubusercontent.com/5235127/206359615-8c7f8e18-749b-419d-a27f-bf7b8278a743.png)

# 🔖 Additional resources

- [Liquibase `loadData`](https://youtu.be/EAsj7OPiEFY?t=1304)
- https://github.com/liquibase/liquibase-neo4j/issues/271

**Comment by michael-simons** [comment]
That’s an interesting request and I can see the reasoning behind it. 

There’s however `LOAD CSV` in cypher directly which is meant for this purpose. I can of course just call that, but the actual file need to be transferred where the database can touch it which somewhat defeats versioned data. 

Writing a csv loader myself in this project is honestly not something I planned. I really think that’s one of the things that don’t belong in a migrations tooling. 

Neo4j has - apart from mentioned cypher command - better alternatives for that.

**Comment by michael-simons** [comment]
Fyi I’m leaving all the things open I plan on working, even if the form may be different.  Thanks a ton for your detailed requests.

**Comment by adriens** [comment]
i @michael-simons , so the best approach for this feature would rather to focus on the liquibase neo4j plugin ?

**Comment by michael-simons** [comment]
Honest advice: neither. Design a data loading process outside your Schema migrations / refactorings. I do think that are very different concerns. That’s the reason I don’t see this feature here. 

Tools to look at:
* Apache Hop https://hop.apache.org/manual/latest/technology/neo4j/index.html
* https://neo4j.com/docs/aura/aurads/importing-data/data-importer/

or just plain load csv https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/

summoning @mattcasters and @jexp for their opinion

**Comment by adriens** [comment]
:grey_question: Would it possible to use [ file() with LOAD CSV](https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/#load-csv-using-file-with-load-csv) directly on a `https` resource :bulb:

**Comment by adriens** [comment]
[Here we GO](https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/#load-csv-import-data-from-a-remote-csv-file)

![image](https://user-images.githubusercontent.com/5235127/206571449-876edb3a-fb4f-4786-8e3a-3298160c1558.png)

**Comment by adriens** [comment]
... but it makes pointing to a specifi GH branch more tricky... which is our case :thought_balloon:

**Comment by michael-simons** [comment]
Thanks for the input, I might have an idea for you that suites your and my approach to this topic.

**Comment by adriens** [comment]
Hmmm, looks like a good teaser :clap:

**Comment by michael-simons** [comment]
Please have a look here: https://github.com/michael-simons/neo4j-migrations/blob/main/extensions/neo4j-migrations-formats-csv/src/test/java/ac/simons/neo4j/migrations/formats/csv/test_migrations/R050__LoadBookData.java

this is how far I would go in supporting you with the described needs.

The base template I added can receive a bit more love and features if needed, but there's little sensible to add I can think of. Please let me know what you think, @adriens

**Comment by adriens** [comment]
Hi @michael-simons , i'm just discovering the his is an [extension](https://github.com/michael-simons/neo4j-migrations/tree/main/extensions) architecture.

Sorry for my ignorance, but would you share some guidelines on how to deal with the extension :pray: :grey_question: 

Some :baby:  questions : 

- Should we manually build the `jar` extension and drop it somewhere ? (as a plugin)
- Which `xml` tag should we use to test the extension ?

**Comment by michael-simons** [comment]
Hey. The extensions are deployed to maven central. The new one will be next week. 

You’ll want to include it in your project and inherit like I do in the test. There’s also an example how to do this for CLI (in the docs). For the new abstract base class you need the new dependency. 

So basically this is then not text (as in cypher or xml) based migration, but a class based one. Programmatic migrations have been possible since the incarnation of this project. I just added the extension which what I think is helpful to deal with your needs.

**Comment by adriens** [comment]
> Hey. The extensions are deployed to maven central. The new one will be next week.

We'll look at it next week as we are proactively working on this topic to better deliver our data at scale with as less effort as possible :smile_cat: 

> So basically this is then not text (as in cypher or xml) based migration, but a class based one. 

Ok, this confirms what I understood : we'll talk about that with the team next week

i'll provide you our feedbacks :+1: 

Thanks a lot for your answsers, it helped a lot.
