### ISSUE TITLE
Newer Versions - GLIBC Error Running In neo4j Docker Image

### ISSUE THREAD

**Issue by MattMencel** [michael-simons/neo4j-migrations#828]
I've been using a Kubernetes Job to run migrations using version `1.4.0` in a `neo4j:latest` image. I run some `cypher-shell` scripts and then `neo4j-migrations`.

I started a new project and have attempted to update to a more recent version and am having trouble with this error.

```
# ./neo4j-migrations -V
./neo4j-migrations: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./neo4j-migrations)
./neo4j-migrations: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./neo4j-migrations)
```

I've tested the `2.0.2` and `1.15.3` versions. Both have this error.

For now, I'll roll back to an older version of neo4j_migrations, but I'd like to figure out what I'm doing wrong.

`neo4j:latest` is Ubuntu based and is running OpenJDK 17.0.5.

**Comment by MattMencel** [comment]
@michael-simons awesome the no-arch package works. If it's slightly slower it doesn't matter for my purposes.  Thanks for the speedy response!

**Comment by michael-simons** [comment]
My pleasure, @MattMencel and thanks again for using Neo4j-Migrations and reporting this.
