### ISSUE TITLE
Provide a mechanism to implement integration tests for Java migrations

### ISSUE THREAD

**Issue by sibethencourt** [michael-simons/neo4j-migrations#829]
I'm not sure if there is a better way of doing this. I'm writing a Java/kotlin `JavaBasedMigration` migration, let's say

`V001_MY_MIGRATION.kt`

I want to implement an integration tests, like so

```
void testMigrationWorks() {
   // ... Creating some data in the database
   V001_MY_MIGRATION().apply()
  // ..verify the data has changed as expected
}
```

I can use an instance of the `Migrations` class to execute the Java migration but it will mark the migrations as processed and that will interfere with other tests. Also I need to write several tests, so the migration should be able to run multiple times for the same database.

The proposal above could work except because it requires a `MigrationContext` which only implementation `DefaultMigrationContext` is private, so I can't use it.

I had to create my own implementation, essentially copying the code from `DefaultMigrationContext`. Is there anything to support this use case?

**Comment by michael-simons** [comment]
Hey @sibethencourt Thanks for using this project and taking the time to report the issue.

I'm happy to support this use case by providing a factory method to get a context instance without going through the actual migration instance. Makes totally sense for me.

**Comment by michael-simons** [comment]
Are you on 2.x or 1.x? I'm only a bit reluctant to back port this new feature and maintain it in two places.

**Comment by michael-simons** [comment]
2.0 is Java 17, the API has not changed in breaking ways.

**Comment by michael-simons** [comment]
In the meantime, here's some example code that should fit your need, maybe you need to mock a bit more, but you get the idea…  I'm using a supplier for the session in the mock so that I can properly close it in my migration. Should work very similar with mockk in Kotlin:


```java
package ac.simons.neo4j.migrations.core;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;
import org.testcontainers.containers.Neo4jContainer;


public class MockContextExampleTest {

	static class MyMigration implements JavaBasedMigration {

		@Override
		public void apply(MigrationContext context) {
			try (var session = context.getSession()) {
				// Whatever you have
				var one = session.run("RETURN 1").single().get(0).asInt();
				Assertions.assertEquals(1, one);
			}
		}
	}

	private static final Neo4jContainer<?> neo4j = new Neo4jContainer<>("neo4j:4.4");

	@BeforeAll
	static void startNeo4j() {
		neo4j.start();
	}

	@AfterAll
	static void stopNeo4j() {
		neo4j.stop();
	}

	@Test
	void example() {

		try (var driver = GraphDatabase.driver(neo4j.getBoltUrl(), AuthTokens.basic("neo4j", neo4j.getAdminPassword()))) {
			var migrationContext = Mockito.mock(MigrationContext.class);
			Mockito.when(migrationContext.getSession()).then(mock -> driver.session());

			new MyMigration().apply(migrationContext);
		}
	}
}
```

**Comment by sibethencourt** [comment]
This `org.neo4j.driver.TransactionContext` seems to be a class for neo4j 5 driver? but we are still in 4.4 but based on the documentation it should work, right? the only one not supported is 4.0?

**Comment by michael-simons** [comment]
Yes, 2.x is based on the driver 5 which works with Neo4j 4.4, Aura and all 5.x versions and most of the 4.x series.

But, as you mention Spring: 
Spring Boot 2.7 uses driver 4.4
Spring Boot 3 uses driver 5

When working on Neo4j-OGM we made an effort to support more than one major version of the driver, but I can't do this in this project. So that's the background of the decision here.

But alas, that's reason enough to bring this feature in both 1.x and 2.x version of this project to help you on older Boot versions.

Your workaround looks good so far.

**Comment by michael-simons** [comment]
I have added a factory method on the interface. This will go out tomorrow during the day in 2.1.0 and 1.16.0, so you still have choices. I hope this works for you.

Thanks again!

**Comment by sibethencourt** [comment]
That is awesome, thank you so much 👍 That will work great

**Comment by michael-simons** [comment]
@all-contributors please add @sibethencourt for ideas
