### ISSUE TITLE
CLI cypher based migration, possibility to run the binary without java dependency.

### ISSUE THREAD

**Issue by amit-kumaryadav** [michael-simons/neo4j-migrations#934]
Hi Micahel, 

I want to run the cypher based migration without java dependency. I tried but I'm getting the below issue. is it possible to run the CLI binary without java, I want to integrate this in CI/CD pipeline to run the migrations. But I'm able to run the CLI binary with java 17 dependency. If it's not possible to run the CLI binary without java then which version is based on java 11 (Current project does not allow java 17).  

![image](https://user-images.githubusercontent.com/36166686/231662054-1ec0a399-70a4-47b2-b07f-0e1882bfad69.png)

Even I tried with other linux version too.

![image](https://user-images.githubusercontent.com/36166686/231671194-7faf41ab-9b27-47b7-bde9-778e04efcbed.png)

![image](https://user-images.githubusercontent.com/36166686/231672281-894b1eb1-d25d-4a5e-8a36-56da62bfb87d.png)

**Comment by michael-simons** [comment]
He Amit, it looks like you are on windows. Are you sure you have downloaded the windows binary? 

https://github.com/michael-simons/neo4j-migrations/releases/download/2.2.2/neo4j-migrations-2.2.2-windows-x86_64.zip

**Comment by amit-kumaryadav** [comment]
Hi Michael, I'm on ubuntu 20 machine

**Comment by michael-simons** [comment]
The first screenshot seems to be the JVM version. The 2nd one is the version you are looking for.
The error printed is expected, see https://github.com/michael-simons/neo4j-migrations/issues/828

You need libc in the container

https://www.graalvm.org/22.0/reference-manual/native-image/StaticImages/

> Mostly static native images statically link against all libraries except libc. This approach is ideal for deploying such native images on distroless container images. Note that it currently only works when linking against glibc.

**Comment by michael-simons** [comment]
Excellent, @amit-kumaryadav and I have to thank you for your request, as we found an issue with the compressed binaries on windows.
