### ISSUE TITLE
ZIP download link is broken

### ISSUE THREAD

**Issue by sdaschner** [michael-simons/neo4j-migrations#96]
The download link to https://repo1.maven.org/maven2/eu/michael-simons/neo4j/neo4j-migrations/0.0.12/neo4j-migrations-0.0.12.zip in the readme is outdated and doesn't work anymore.

Apparently, the Maven repo has been migrated to repo.maven.apache.org, however, the following folder only contains the ZIP file: https://repo.maven.apache.org/maven2/eu/michael-simons/neo4j/neo4j-migrations/0.0.12/

Searching for the ZIP 0.0.12 archive via search.maven.org worked, but there is probably a better way to link it directly.

**Comment by michael-simons** [comment]
Thanks, Sebastian. 👍
